# Generated by Django 4.0.6 on 2022-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='date_birth',
            field=models.DateField(null=True),
        ),
    ]
